name: BinderDH

on:
  push:
    branches:
      - master
      - develop
      - feature

jobs:
  BinderDH:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to Docker Hub
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: paveloom
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        COMMIT_MSG: "Binder: update the image tag."
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: "paveloom/scats.jl-binder"