name: Binder (gh-pages)

on:
  push:
    branches:
      - master

jobs:
  GHPagesBinder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        base: master
        filters: |
          binder:
            - 'binder/**/*'

    - name: Update the Dockerfile
      if: steps.filter.outputs.binder == 'true'
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: binder
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 🚫 Aborted.
      if: steps.filter.outputs.binder != 'true'
      run: echo The action was cancelled because no changes were found to the `binder` folder.