name: VersionCheck

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  VersionCheck_master:

    name: VersionCheck Job (master)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Получение истории коммитов
      run: git fetch --prune --unshallow origin +refs/heads/*:refs/remotes/origin/*
    - name: Вызов скрипта для проверки версии
      run: bash .github/scripts/VersionCheck\ \(master\).sh